export const PROJECTS = [
  {
    type: "team",
    title: "Petple",
    icon: "/src/assets/images/petple_icon.png",
    status: "working",
    description:
      "반려 동물이라는 키워드로 모이는 사람들을 위해 다양한 서비스와 커뮤니티 기능을 제공하는 웹 서비스입니다.",
    main_task: ["커뮤니티 게시판CRUD", "위치 기반 실시간 채팅 기능"],
    role: "Full-Stack (Frontend 50% / Backend 50%)",
    techStack: [
      "TypeScript",
      "React",
      "Express",
      "MongoDB",
      "Docker",
      "Socket.io",
      "Zustand",
      "Tanstack-Query",
    ],
    repoFront: "https://github.com/DonggunLim/Petple_front",
    repoBack: "https://github.com/DonggunLim/Petple_back",
    web: "https://petple-front.vercel.app",
  },
  {
    type: "team",
    title: "BlahBlah",
    icon: "/src/assets/images/blahblah_icon.svg",
    status: "working",
    description:
      "사용자가 직접 원하는 주제로 게시판을 만들어 커뮤니티 형성을 제공해주는 웹 서비스 입니다.",
    role: "Full-Stack (Frontend 50% / Backend 50%)",
    techStack: ["TypeScript", "React", "Express", "MongoDB", "Mongoose"],
    repoFront: "https://github.com/DonggunLim/Blahblah_front",
    repoBack: "https://github.com/DonggunLim/Blahblah_back",
    web: "https://blahblah-front.vercel.app",
  },
  {
    type: "team",
    title: "WorkPlus",
    icon: "/src/assets/images/workplus_icon.png",
    status: "working",
    description: "업무 지원 플랫폼이라는 주제로 진행한 웹 프로젝트 입니다.",
    role: "팀장 (Backend 100%, Frontend 50%)",
    techStack: [
      "JavaScript",
      "React",
      "Express",
      "MongoDB",
      "Mongoose",
      "TypeScript",
    ],
    repoFront: "https://github.com/DonggunLim/WorkPluse_front",
    repoBack: "https://github.com/DonggunLim/WorkPlus_back",
    web: "https://work-plus-front.vercel.app",
  },
  {
    type: "personal",
    title: "React-UI-Kit",
    icon: "/src/assets/images/react.png",
    description:
      "Headless 스타일 및 Compound Pattern을 활용한 React UI 컴포넌트 라이브러리 입니다.",
    techStack: ["TypeScript", "React", "Vite"],
    repo: "https://github.com/DonggunLim/react-ui-kit",
    npm: "https://www.npmjs.com/package/@imdonggun/react-ui-kit",
  },
  {
    type: "personal",
    title: "Vite-Plugin-Generate-Todo",
    icon: "/src/assets/images/vite.png",
    description:
      "소스 코드 내의 주석을 자동으로 추출하여 TODO.md 파일로 생성하는 Vite 플러그인 입니다.",
    techStack: ["TypeScript", "Vite", "Vite Plugin API", "Node.js"],
    repo: "https://github.com/DonggunLim/vite-plugin-generate-todo",
    npm: "https://www.npmjs.com/package/vite-plugin-generate-todo",
  },
];
